### ISSUE TITLE
check-eclipse fails with NoSuchMethodError: org.gradle.logging.ProgressLogger.setDescription(Ljava/lang/String;)V with gradle 2.6+

### ISSUE THREAD

**Issue by sarod** [stempler/bnd-platform#7]
Using bnd-platform on gradle 2.6+ fails with NoSuchMethodError: org.gradle.logging.ProgressLogger.setDescription(Ljava/lang/String;)

This seems related to https://github.com/michel-kraemer/gradle-download-task/issues/29

**Comment by michel-kraemer** [comment]
@stempler if the issue is related to gradle-download-task then just update it. The problem doesn't appear in later versions anymore.

**Comment by stempler** [comment]
Thanks for the hint! I updated the gradle-download-task dependency (025e38b8e380263827a53c446b5aed4d25d847a3) and released version `1.3.0` of bnd-platform. I only tested with Gradle 2.10 so far, but it should work with 2.6+ as well.
